[package]
name = "day22"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
divan = "0.1.17"
rayon = "1.10.0"


[[bench]]
name = "day22-bench"
path = "benches/benchmarks.rs"
harness = false
