[package]
name = "day23"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
divan = "0.1.17"
petgraph = "0.6.5"


[[bench]]
name = "day23-bench"
path = "benches/benchmarks.rs"
harness = false
